setwd("C:/Users/Tigmanshu/Documents/pgh_streets/pgh_streets/pgh_streets")
library(rgdal)
s1 <- readOGR(".","pgh_streets")
summary(s1)
s2 <- s1[s1$LENGTH>0.05980,]
spplot(s2,z="LENGTH")
setwd("C:/Users/Tigmanshu/Documents/Spatial Data Analytics")
load("lnd.Rdata")
load("stations.RData")
summary(lnd)
summary(stations)
data.frame(stations)
stationsagg<-aggregate(stations["Value"],by=lnd, FUN = mean)
print(stationsagg$Value)
spplot(stationsagg,z="Value",main=list(label="Map of London County with Station values"))
relation<-lm(stations$Value~stations$coords.x1+stations$coords.x2)
print(relation)
plot(relation)
centroids <- getSpPPolygonsLabptSlots(lnd)
relation<-lm(stationsagg$Value~centroids[,1]+centroids[,2])
print(relation)
plot(relation)